name: Contributors List
description: | 
  Writes the contributors.json file to be read by the Unity project.
  Please note the API shortcomings: https://docs.github.com/en/rest/repos/repos#list-repository-contributors
  If we have more than 100 contributors, we need to page the result.
  If we have more than 500 contributors, not all will be shown anymore.
inputs:
  github-token:
    required: true
    description: GitHub Token
outputs:
  content:
    description: The JSON string containing build information.
    value: ${{ steps.content.outputs.value }}
  
runs:
  using: 'composite'
  steps:
    - name: Get Contributors from API
      id: variables
      env:
        GH_TOKEN: ${{ inputs.github-token }}
      run: |
        echo "::set-output name=contributors::$(gh api /repos/BoundfoxStudios/community-project/contributors | jq --compact-output '[.[] | { user: .login, url: .html_url, contributions: .contributions }]')"
      shell: sh
    - name: Write Build Manifest to JSON file
      id: content
      uses: mkungla/actions-set-text-output@v1
      with:
        text: ${{ steps.variables.outputs.contributors }}
