name: Project Management

concurrency: ${{ github.event.issue.number }}

on:
  issue_comment:
    types:
      - created
      - edited
  issues:
    types:
      - opened
      - unlabeled
      - assigned
      - unassigned

jobs:
  assign-issue-to-contributor:
    name: Assign Issue to Contributor
    if: ${{ github.event_name == 'issue_comment' && !github.event.issue.pull_request && !contains(github.event.issue.labels.*.name, 'Triage') }}
    runs-on: ubuntu-latest
    steps:
      - uses: Bhacaz/checkout-files@v2
        with:
          files: .github/actions
      - name: Assign issue
        uses: bdougie/take-action@main
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          message: Danke, dass Du diese Aufgabe übernimmst! Falls Du Fragen hast, schreib sie einfach ins Issue!
          issueCurrentlyAssignedMessage: Die Aufgabe wird aktuell bereits von jemand anderem bearbeitet, daher kannst Du Dir diese leider nicht selbst zuweisen.
          trigger: .meine-aufgabe
      - uses: ./.github/actions/move-issue
        with:
          app-id: ${{ secrets.COMMUNITY_APP_ID }}
          private-key: ${{ secrets.COMMUNITY_APP_PEM }}
          issue-id: ${{ github.event.issue.node_id }}
          column: In Progress
  
  move-new-issues-to-triage-column:
    name: Move new issues to triage column
    if: ${{ github.event_name == 'issues' && github.event.action == 'opened' }}
    runs-on: ubuntu-latest
    steps:
      - uses: Bhacaz/checkout-files@v2
        with:
          files: .github/actions
      - uses: ./.github/actions/move-issue
        with:
          app-id: ${{ secrets.COMMUNITY_APP_ID }}
          private-key: ${{ secrets.COMMUNITY_APP_PEM }}
          issue-id: ${{ github.event.issue.node_id }}
          column: Triage
  
  move-issue-to-todo-column-when-triage-label-is-removed:
    name: Move an issue to the Todo column when triage label is removed
    if: ${{ github.event_name == 'issues' && github.event.action == 'unlabeled' && github.event.label.name == 'Triage' }}
    runs-on: ubuntu-latest
    steps:
      - uses: Bhacaz/checkout-files@v2
        with:
          files: .github/actions
      - uses: ./.github/actions/move-issue
        with:
          app-id: ${{ secrets.COMMUNITY_APP_ID }}
          private-key: ${{ secrets.COMMUNITY_APP_PEM }}
          issue-id: ${{ github.event.issue.node_id }}
          column: Todo
  
  move-issue-to-in-progress-on-assign:
    name: Move an issue to in progress when it is assigned.
    if: ${{  github.event_name == 'issues' && github.event.action == 'assigned' }}
    runs-on: ubuntu-latest
    steps:
      - uses: Bhacaz/checkout-files@v2
        with:
          files: .github/actions
      - uses: ./.github/actions/move-issue
        with:
          app-id: ${{ secrets.COMMUNITY_APP_ID }}
          private-key: ${{ secrets.COMMUNITY_APP_PEM }}
          issue-id: ${{ github.event.issue.node_id }}
          column: In Progress

  move-issue-back-to-todo-on-unassign:
    name: Move an issue back to todo on unassign
    if: ${{  github.event_name == 'issues' && github.event.action == 'unassigned' && !github.event.issue.assignee }}
    runs-on: ubuntu-latest
    steps:
      - uses: Bhacaz/checkout-files@v2
        with:
          files: .github/actions
      - uses: ./.github/actions/move-issue
        with:
          app-id: ${{ secrets.COMMUNITY_APP_ID }}
          private-key: ${{ secrets.COMMUNITY_APP_PEM }}
          issue-id: ${{ github.event.issue.node_id }}
          column: Todo