name: Release
concurrency: no-concurrency-due-to-license-activation

on: 
  push:
    branches:
      - main

jobs: 
  build:
    name: Release
    uses: ./.github/workflows/build.yml
    secrets:
      UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
      UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
      UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
    with:
      do-test: true
      fail-fast: true
      max-parallel: 1